image_list:
  1:
    caption_html: |
      1993-94 poster from <a href="/catalog/uamensbasketballposters_aspace_ref98_ngq">
      Men's Basketball Poster Collection</a>
    image: dbpst003001.jpg
  2:
    caption_html: |
      Duke Chapel window from <a href="/catalog/uaduchapelill_aspace_e08929103acb6a3679d7b7590c0b98fc">
      Duke Chapel Illuminated photographs</a>
    image: dcist001008001.jpg
  3:
    caption_html: |
      East Campus, 1925 from <a href="/catalog/uapropplat_aspace_ref13_vib">
      Duke Property Plats</a>
    image: dppsi010010100.jpg
  4:
    caption_html: |
      Scrapbook of tobacco trading cards, <a href="/catalog/dukeandsons_aspace_ref79_zil">
      W. Duke, Sons & Co. Advertising Materials</a>
    image: dscsi070010230.jpg
  5:
    caption_html: |
      Child in Tiger Costume, from the <a href="/catalog/gamblesidney">Sidney D. Gamble
      Photographs</a>
    image: gamble_258A_1474.jpg
  6:
    caption_html: |
      Photograph N318, from <a href="catalog/mangumhugh_aspace_ref31_lhf">Hugh Mangum
      Photographs</a>
    image: hmpgp123180000.jpg
  7:
    caption_html: |
      Prosthetic glass eyeballs from <a href="/catalog/homartifacts_aspace_ref1241_u4n">
      History of Medicine Artifacts Collection</a>
    image: homst03008001.jpg
  8:
    caption_html: |
      Passive resistance training, SNCC from <a href="/catalog/karalesjames_aspace_ref410_pdt">
      James H. Karales photographs</a>
    image: kfpst0030060010.jpg
  9:
    caption_html: |
      Alix Shulman holding poster, Miss America protest, Atlantic City, 1968, from the
      <a href="/catalog/shulmanalix">Alix Kates Shulman Papers</a>
    image: maddc070610010.jpg
  10:
    caption_html: |
      Freedom Trash Can, Miss America protest, Atlantic City, 1968, from the
      <a href="/catalog/shulmanalix">Alix Kates Shulman Papers</a>
    image: maddc070630010.jpg
  11:
    caption_html: |
      Watercolor sketches, 1906-1907, in the
      <a href="/catalog/stewartharrietsanderson_aspace_ref14_5db">
      Harriet Sanderson Stewart Diaries</a>
    image: wtddy100043130.jpg
  12:
    caption_html: |
      Mountaineering, optical lantern transparency from
      <a href="/catalog/womantheworldover_aspace_14792452e1b28986b7ca542c95e29990">
      Woman: The World Over</a>
    image: wwost001028001.jpg
  13:
    caption_html: |
      Kool Cigarettes Billboard, from the <a href="/catalog/rcmaxwellco_aspace_ref625_fw8">
      R.C. Maxwell Company Records</a>
    image: XXX4740.jpg
  14:
    caption_html: |
      Woman and dogs, Western North Carolina, from the
      <a href="/catalog/harrisalex_aspace_a0bd0ebe41ea36ec57a17a56af56810d">Alex Harris
      Photographs</a>
    image: ahpst002013.jpg
  15:
    caption_html: |
      Soviet merchant, 1930 from <a href="/catalog/fetter_aspace_ref1767_uq9">Frank Whitson
      Fetter papers</a>
    image: esrph010010290.jpg
  16:
    caption_html: |
      NC Mutual Life Insurance Office, Parrish Street, Durham, in the
      <a href="/catalog/ncmutual_aspace_ref1194_ihw">NC Mutual Archives</a>
    image: ncmst001.jpg
  17:
    caption_html: |
      Early Motorola television, 1948, from the
      <a href="/catalog/rcmaxwellco_aspace_ref679_po2">R.C. Maxwell Company Records</a>
    image: XXH2867.jpg
  18:
    caption_html: |
      John Quincy Adams letter to Benjamin Rush, 1811, in the
      <a href="/catalog/rushbenjaminandjulia_aspace_43c9e6c4a080a76a450f8ef1ae2f99d7">
      Benjamin and Julia Stockton Rush Papers</a>
    image: brpst002001.jpg
  19:
    caption_html: |
      Letter from W. E. B. DuBois to A. B. Hunter, 1898, in the
      <a href="/catalog/huntercharles_aspace_ref24_a84">Charles N. Hunter Papers</a>
    image: cnhms01005031.jpg
  20:
    caption_html: |
      African American soldiers, 1945, from
      <a href="/catalog/aframersoldiersalbum3909th_aspace_396e50a94e2d3e2b10c211a58493736f">
      African American soldier's World War II photograph album</a> (page 9)
    image: afrst01001009.jpg
  21:
    caption_html: |
      African American soldiers, 1946, from
      <a href="/catalog/millermaynard_aspace_ref14_025">Maynard Miller photograph
      album of occupied Japan</a> (page 7)
    image: afrst08001007.jpg
